<a href="https://colab.research.google.com/github/Arun-cseds/python-programing/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUmpy in python



In [ ]:
import numpy as np


In [ ]:
l1=np.array([10,20,30,40])

In [ ]:
l1

array([10, 20, 30, 40])

In [ ]:
type(l1)

numpy.ndarray

In [ ]:
#multidimensional array

In [ ]:
l2=[[10,20,30,40],[40,50,60,70]]

In [ ]:
n=np.array(l2)
n

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [ ]:
n1=np.zeros((0,0))
n1


array([], shape=(0, 0), dtype=float64)

In [ ]:
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n4=np.full((2,2),10)
n4

array([[10, 10],
       [10, 10]])

In [ ]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
n2=np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
n=np.random.randint(1,100,5)
n

array([72,  6, 90, 96, 47])

In [ ]:
n1=np.random.randint(1,50,10)
n1

array([16, 18,  7, 19, 28, 21, 19, 31, 36, 47])

In [ ]:
n1.shape

(10,)

In [ ]:
n=np.array([[1,2,3],[4,5,6]])
n.shape

(2, 3)

In [ ]:
n.shape=(3,2)
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
n.shape=(6,1)
n

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [ ]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [ ]:
n1=np.array([10,20,30])
np.sum([n1])

60